# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/protocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12src/protocol.proto\x12\tstar_simu\"\xf0\x01\n\x0eSatelliteState\x12\x11\n\ttimestamp\x18\x01 \x01(\r\x12\r\n\x05pos_x\x18\x02 \x01(\x01\x12\r\n\x05pos_y\x18\x03 \x01(\x01\x12\r\n\x05pos_z\x18\x04 \x01(\x01\x12\r\n\x05vel_x\x18\x05 \x01(\x01\x12\r\n\x05vel_y\x18\x06 \x01(\x01\x12\r\n\x05vel_z\x18\x07 \x01(\x01\x12\x0e\n\x06quat_x\x18\x08 \x01(\x02\x12\x0e\n\x06quat_y\x18\t \x01(\x02\x12\x0e\n\x06quat_z\x18\n \x01(\x02\x12\x0e\n\x06quat_w\x18\x0b \x01(\x02\x12\x0f\n\x07omega_x\x18\x0c \x01(\x02\x12\x0f\n\x07omega_y\x18\r \x01(\x02\x12\x0f\n\x07omega_z\x18\x0e \x01(\x02\"I\n\nVisionData\x12\x11\n\ttimestamp\x18\x01 \x01(\r\x12\t\n\x01u\x18\x02 \x01(\x05\x12\t\n\x01v\x18\x03 \x01(\x05\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.protocol_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SATELLITESTATE._serialized_start=34
  _SATELLITESTATE._serialized_end=274
  _VISIONDATA._serialized_start=276
  _VISIONDATA._serialized_end=349
# @@protoc_insertion_point(module_scope)
